name: union-type

dependencies:
  - base
  - exceptions
  - mmorph
  - mtl

when:
  - condition: impl(ghc >=7.10)
    cpp-options: -DDEPRECATED_LANGUAGE_OVERLAPPING_INSTANCES

ghc-options:
  - -Wall

library:
  source-dirs: [src]
